# Generated by Django 2.2.6 on 2019-11-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0003_article_article_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entityresolution',
            old_name='resolution',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='entityresolution',
            old_name='resolution_index',
            new_name='resolution_id',
        ),
        migrations.AddField(
            model_name='entityresolution',
            name='original_type',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='entityresolution',
            name='paragraph',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entityresolution',
            name='sentence',
            field=models.IntegerField(default=0),
        ),
    ]
