# Generated by Django 3.0.3 on 2020-04-13 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0006_userarticles'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='validated',
        ),
    ]
