# Generated by Django 3.0.3 on 2020-06-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0008_auto_20200429_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryResolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('entity_id', models.IntegerField(default=0)),
            ],
        ),
    ]
