# Generated by Django 2.2.6 on 2019-11-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.TextField(default='news_article'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='media_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='publish_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='article',
            name='subtitle',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
